### ISSUE TITLE
Form Control Color width is too narrow

### ISSUE THREAD

**Issue by pzandre** [dengunorg/django-admin-kubi#10]
The Colorfield width is too narrow, making it impossible to enter values manually.

![image](https://github.com/dengunorg/django-admin-kubi/assets/56031171/2f46441b-2c48-427b-8b52-afb102e4f222)

https://github.com/dengunorg/django-admin-kubi/blob/f755f16fded66cd60f9ca9ad714029f1c0a3a0aa/django_admin_kubi/assets/css/app.css#L2246

**Comment by gunsmoke** [comment]
@pzandre added support for django-colorfield on v1.0.6
