### ISSUE TITLE
Logout isn't working in Django 5

### ISSUE THREAD

**Issue by andrew-gardener** [dengunorg/django-admin-kubi#11]
Logout via Get requests was deprecated in v4.1 (https://docs.djangoproject.com/en/4.1/releases/4.1/#log-out-via-get) and doesn't work in v5.

Switching the logout link to a post form should fix this https://github.com/dengunorg/django-admin-kubi/blob/b17a4cec653ffadddeba8a1354275c93e8a1abdf/django_admin_kubi/templates/admin/menu.html#L56

**Comment by gunsmoke** [comment]
Thanks @andrew-gardener, should be fixed in latest version == v1.0.7
