### ISSUE TITLE
Deprecated templatetag `length_is` causes an error in Django 5.1

### ISSUE THREAD

**Issue by jaredni** [dengunorg/django-admin-kubi#16]
`length_is` template is removed in [Django 5.1](https://docs.djangoproject.com/en/dev/releases/5.1/#features-removed-in-5-1)
`length_is` is deprecated in favor of `length` [docs](https://docs.djangoproject.com/en/dev/releases/4.2/#id1)

In template `/usr/local/lib/python3.11/site-packages/django_admin_kubi/templates/admin/includes/fieldset.html`, error at line 25

**Comment by gunsmoke** [comment]
@jaredni fixed on latest version v1.1.0 release
